### ISSUE TITLE
R CMD CHECK failures

### ISSUE THREAD

**Issue by bpbond** [kaizadp/nmrrr#2]
Hi @kaizadp , a few questions:

## Tests

Right now the tests fail on my system:
```
── Failure (test-processing.R:31:3): import-spectra works ──────────────────────
`spectra_test` (`actual`) not equal to `spectra_old` (`expected`).
```
Is this known? Do you know what's going on?

## No visible binding

At the moment checking the package produces lots of CRAN notes of the form
```
  assign_compound_classes: no visible binding for global variable ‘group’
```
This is a consequence of using dplyr and more specifically its [nonstandard evaluation](http://adv-r.had.co.nz/Computing-on-the-language.html). If we're going to stick to this approach, we should clean up the warnings.

## Documentation

```
  prepare_Rd: assign_compound_classes.Rd:22-24: Dropping empty section \examples
```

Similarly, there lots of messages like this...

**Comment by bpbond** [comment]
Most important first question: what's up with the test failures? I just want to understand whether this is something about my system, or if they're failing on your side too. Thanks!

**Comment by kaizadp** [comment]
## Tests

I had the same test failures. There was some mismatch at the lower intensities (see screenshot). I must have made a small tweak to the code after uploading the test file, which I missed. I made a new test file, and it ran ok on my computer. 807e603237807975b9a2bed8ae8b9f1bb8dc5bcc

![image](https://user-images.githubusercontent.com/50244730/152844887-aa74f2fa-317b-4b86-bf08-cdf1188d0190.png)


## No visible binding
Can we tell if these notes are for specific commands/lines, or just because we're using dplyr in general? I am partial to using `tidyverse` packages, but maybe we need to revisit that?


## Documentation
I haven't completely filled all the sections in there, I figured I'd leave those in as placeholders for now, so I can go back and add info later.

**Comment by bpbond** [comment]
1 - OK. Be aware that we'll want to define a tolerance to any comparison like this; computers get bit wiggles that can cause spurious mismatches.

2 - The tidyverse can be great for data analyses; I'm quite a bit warier of it for package development. See for example https://recology.info/2018/10/limiting-dependencies/

3 - Sounds good

**Comment by bpbond** [comment]
Cleaned up failures.
